#!/usr/bin/env python3
"""Python side of the golden mask corpus (tests/mask-golden.json, mask parity spec section 8).

Every case must give exactly its "masked" text and all seven "counts" from
ts_common.mask_detail, with a temporary TYPESAFE_NAMES_FILE that holds exactly the
header's "names" (synthetic), so the private ~/.config/typesafe/names.txt is never read.
The file is generated by tests/gen_mask_golden.py; imprint-core checks the same file
against its Go port. A file without cases, or with a case count other than the
header's, fails. A Python whose unicodedata version differs from the header's skips the
case check with a message: the expected outputs depend on the Unicode tables.
"""
import json
import os
import sys
import tempfile
import time
import unicodedata
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
import ts_common as tc  # noqa: E402

GOLDEN = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mask-golden.json")


class TestMaskGolden(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with open(GOLDEN, "r", encoding="utf-8") as f:
            cls.data = json.load(f)
        cls.header, cls.cases = cls.data["header"], cls.data["cases"]
        fd, cls.names_path = tempfile.mkstemp(prefix="typesafe-golden-names-", suffix=".txt")
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write("".join(name + "\n" for name in cls.header["names"]))
        cls.prev = os.environ.get("TYPESAFE_NAMES_FILE")
        os.environ["TYPESAFE_NAMES_FILE"] = cls.names_path
        tc.get_name_regex(cls.names_path)

    @classmethod
    def tearDownClass(cls):
        if cls.prev is None:
            os.environ.pop("TYPESAFE_NAMES_FILE", None)
        else:
            os.environ["TYPESAFE_NAMES_FILE"] = cls.prev
        os.remove(cls.names_path)

    def test_header(self):
        self.assertGreater(len(self.cases), 0, "mask-golden.json holds no cases")
        self.assertEqual(len(self.cases), self.header["case_count"],
                         "case count differs from the header's case_count")
        self.assertEqual(self.header["categories"], list(tc.DEFAULT_CATEGORIES))
        self.assertTrue(self.header["names"], "header holds no names")

    def test_cases(self):
        want = self.header["unidata_version"]
        if want != unicodedata.unidata_version:
            self.skipTest("mask-golden.json was generated with unicodedata %s, this Python has %s; "
                          "run it with a Python whose unicodedata is %s, or regenerate with "
                          "tests/gen_mask_golden.py and review the diff" % (want, unicodedata.unidata_version, want))
        failures = []
        t0 = time.perf_counter()
        for case in self.cases:
            masked, counts = tc.mask_detail(case["text"])
            if masked != case["masked"] or counts != case["counts"]:
                failures.append("%s: text %s\n  want %s %s\n  got  %s %s" % (
                    case["id"], ascii(case["text"]), ascii(case["masked"]), case["counts"], ascii(masked), counts))
        if failures:
            self.fail("%d of %d cases differ (%.2f s); the first ones:\n%s" % (
                len(failures), len(self.cases), time.perf_counter() - t0, "\n".join(failures[:10])))


if __name__ == "__main__":
    unittest.main()
